### PR TITLE
Proposal to fix #1

### LINKED ISSUE #1: Write output and error to a file
In the systemd service definition right now output and error are redirected to standard output.
Provide a runnable configuration for redirect them to a file, for both output (aka service-output.log ) and error ( aka service-error.log )

### PR DESCRIPTION
**Pull request by mirkoperillo**
Hi @albertotn,

this is my proposal to fix #1

### CODE REVIEW

**Comment by albertotn** [comment]
For me it's fine, just one quick question: it's better to put a log file for a service under /var/log ?
Or in the case of Systemd "log into" journal, so it's more easy to gather with Journalctl  ?

**Comment by mirkoperillo** [comment]
I have put `/tmp` only as an example, if you prefer I can change directory to `/var/log`.
Let me know

**Comment by albertotn** [comment]
I think is better to put them under /var/log

**Comment by mirkoperillo** [comment]
@albertotn done

**Pull request merged**
